version: '2'
services:
  mysql:
   image: mysql:latest
   ports:
     - "3306:3306"
   container_name: mysql-docker
   network_mode: host
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: movieDb
     MYSQL_USER: app_root
     MYSQL_PASSWORD: root123

  spring:
    image: mano2020/moviecruiser:spring-image
    restart: always
    network_mode: host
    container_name: spring-docker
    depends_on:
      - mysql
    ports:
      - 8080:8080

  angular:
    image: mano2020/moviecruiser:angular-image
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
