spring:
  datasource:
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect
   hibernate:
    ddl-auto: update
   show-sql: true
